export type Country = { name: string; code: string; dial: string }

export const COUNTRIES: Country[] = [
  { name: "Nederland", code: "NL", dial: "+31" },
  { name: "België", code: "BE", dial: "+32" },
  { name: "Duitsland", code: "DE", dial: "+49" },
  { name: "Frankrijk", code: "FR", dial: "+33" },
  { name: "Verenigd Koninkrijk", code: "GB", dial: "+44" },
  { name: "Luxemburg", code: "LU", dial: "+352" },
  { name: "Spanje", code: "ES", dial: "+34" },
  { name: "Portugal", code: "PT", dial: "+351" },
  { name: "Italië", code: "IT", dial: "+39" },
  { name: "Oostenrijk", code: "AT", dial: "+43" },
  { name: "Zwitserland", code: "CH", dial: "+41" },
  { name: "Ierland", code: "IE", dial: "+353" },
  { name: "Denemarken", code: "DK", dial: "+45" },
  { name: "Zweden", code: "SE", dial: "+46" },
  { name: "Noorwegen", code: "NO", dial: "+47" },
  { name: "Finland", code: "FI", dial: "+358" },
  { name: "IJsland", code: "IS", dial: "+354" },
  { name: "Polen", code: "PL", dial: "+48" },
  { name: "Tsjechië", code: "CZ", dial: "+420" },
  { name: "Slowakije", code: "SK", dial: "+421" },
  { name: "Hongarije", code: "HU", dial: "+36" },
  { name: "Roemenië", code: "RO", dial: "+40" },
  { name: "Bulgarije", code: "BG", dial: "+359" },
  { name: "Griekenland", code: "GR", dial: "+30" },
  { name: "Cyprus", code: "CY", dial: "+357" },
  { name: "Malta", code: "MT", dial: "+356" },
  { name: "Kroatië", code: "HR", dial: "+385" },
  { name: "Slovenië", code: "SI", dial: "+386" },
  { name: "Servië", code: "RS", dial: "+381" },
  { name: "Bosnië en Herzegovina", code: "BA", dial: "+387" },
  { name: "Albanië", code: "AL", dial: "+355" },
  { name: "Noord-Macedonië", code: "MK", dial: "+389" },
  { name: "Litouwen", code: "LT", dial: "+370" },
  { name: "Letland", code: "LV", dial: "+371" },
  { name: "Estland", code: "EE", dial: "+372" },
  { name: "Oekraïne", code: "UA", dial: "+380" },
  { name: "Rusland", code: "RU", dial: "+7" },
  { name: "Turkije", code: "TR", dial: "+90" },
  { name: "Marokko", code: "MA", dial: "+212" },
  { name: "Egypte", code: "EG", dial: "+20" },
  { name: "Suriname", code: "SR", dial: "+597" },
  { name: "Curaçao / Bonaire / Sint Maarten", code: "CW", dial: "+599" },
  { name: "Aruba", code: "AW", dial: "+297" },
  { name: "Kaapverdië", code: "CV", dial: "+238" },
  { name: "Ghana", code: "GH", dial: "+233" },
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Eritrea", code: "ER", dial: "+291" },
  { name: "Somalië", code: "SO", dial: "+252" },
  { name: "Zuid-Afrika", code: "ZA", dial: "+27" },
  { name: "Syrië", code: "SY", dial: "+963" },
  { name: "Irak", code: "IQ", dial: "+964" },
  { name: "Iran", code: "IR", dial: "+98" },
  { name: "Afghanistan", code: "AF", dial: "+93" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "China", code: "CN", dial: "+86" },
  { name: "Japan", code: "JP", dial: "+81" },
  { name: "Indonesië", code: "ID", dial: "+62" },
  { name: "Filipijnen", code: "PH", dial: "+63" },
  { name: "Vietnam", code: "VN", dial: "+84" },
  { name: "Thailand", code: "TH", dial: "+66" },
  { name: "Australië", code: "AU", dial: "+61" },
  { name: "Verenigde Staten / Canada", code: "US", dial: "+1" },
  { name: "Brazilië", code: "BR", dial: "+55" },
]
